.TH countalpha 1
.UC 4
.SH NAME
countalpha \- counts the number of times the letters a - z occur and
computes a probability model.
.SH SYNOPSIS
.HP
.B countalpha  file1  file2
.SH DESCRIPTION
This program counts the number of times the letters a-z occur in
file1 and computes a probability model.  The probability model is written
in file2.  The program does not distinguish between upper and lower
case letters.

The program does not need any subroutines.

.SH AUTHOR
Khalid Sayood, University of Nebraska - Lincoln.


