.TH distau
.UC 4
.SH NAME
distau \- computes various performance measures between original and 
reconstructed speech and audio files.
.SH SYNOPSIS
.HP
.B distau  file1  file2
[
.B \-h
]
.SH DESCRIPTION
This program computes the mean squared error, mean absolute error, and
signal to noise ratio (in dB), between file1 and file2.  It assumes file1 to 
be the original speech/audio and file2 to be the reconstructed speech/audio.  
The samples are assumed to be 16 bit uniformly quantized stored in raw format.  

If A[i] is the i'th sample value of the original (file1),
R[i] is the i'th sample value of the reconstructed speech/audio,
and < > denotes average value, then
the performance measures computed by this program are defined as follows.

mean squared error = <(A[i] - R[i])^2>.

mean absolute error = <|A[i] - R[i]|>.

signal to noise ratio = <A[i]^2> / <(I[i,j] - R[i])^2>.


The program needs the following subroutines:
.IP readau
.IP get_file_size
.LP
and the header file idc.h


.SH AUTHOR
Khalid Sayood, University of Nebraska - Lincoln.


