.TH entfile 1
.UC 4
.SH NAME
entfile \- computes the zero order entropy of a a file.
.SH SYNOPSIS
.HP
.B entfile  file
.SH DESCRIPTION
This program counts the number of times different eight bit characters
in a file occur, uses the counts to generate a zero order probability model,
and then computes the entropy for this model.

The program needs the subroutine ent.

.SH AUTHOR
Khalid Sayood, University of Nebraska - Lincoln.


