.TH vqimg_dec 1 
.UC 4
.SH NAME
vqimg_dec \- reconstructs an image compressed using vqimg_enc.
.SH SYNOPSIS
.HP
.B vqimg_dec
[
.BI \-i " cmpfile"
][
.BI \-o " imageout"
][
.B \-h
]
.SH DESCRIPTION
This program reconstructs an image which had been compressed using 
vqimg_enc.  The codebook used to compress the image is needed along with
the compressed image.  The name of the codebook is read from the compressed
file.  If an input file is not specified the input is read from standard in.
If an output file is not specified the output is written to standard out.  
The images are 8 bit grey-level images stored using raster scan
order.

The program needs the following subroutines:
.IP unstuff
.LP
and the header file idc.h

.SH OPTIONS
.TP
.BI \-i " cmpfile"
This is the compressed file.  The file also contains the name of the 
codebook used during vector quantization.
.TP
.BI \-o " imageout"
This is the reconstructed image.  It is assumed that this image is 
a grey scale (8 bits/pixel) image and is stored in raster scan order.
.TP
.BI \-h
This option will provide the usage.

.SH AUTHOR
Khalid Sayood, University of Nebraska - Lincoln.


